config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  resources :posts
  resources :invasive_species do
    resources :posts, except: [:index]
  end

  resources :users

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home   
    end
end

app/views/welcome/_form.html.erb
Using this file to temporarily store code templates

<%= form_with(model: ) do |f| %>
    <%= f.label : %>
    <%= f.text_field : %><br>

    <%= f.label : %>
    <%= f.text_field : %><br>
    
    <%= f.label : %>
    <%= f.text_area : %><br>

    <%= f.label : %>
    <%= f.text_field : %><br>

    <%= f.label : %>
    <%= f.password_field : %><br>

    <%= f.label : %>
    <%= f.password_field : %><br>

    <%= f.submit %>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome to Plant.Spy!</h1>

<h3>A place for aspiring and professional botanists to track the progress of invasive species.</h3>

<h4>Please <%= link_to "Login", login_path %> or <%= link_to "Sign Up", signup_path %> to add to our community. </h4>

app/views/welcome/template_code.html.erb
Using this file to temporarily store code templates

 <%# bootstrap code begins %>
    <%# <link href="/assets/bootstrap.min.css" media="all" rel="stylesheet" /> %>
    <%# <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"> %>

   <%# <script src="/assets/bootstrap.min.js"></script> %>

    <%# <script src="js/bootstrap.min.js"></script> %>
  <%# bootstrap code ends %>

BASIC FORM WITH
<%= form_with(model: ) do |f| %>
    <%= f.label : %>
    <%= f.text_field : %><br>

    <%= f.label : %>
    <%= f.text_field : %><br>
    
    <%= f.label : %>
    <%= f.text_area : %><br>

    <%= f.label : %>
    <%= f.text_field : %><br>

    <%= f.label : %>
    <%= f.password_field : %><br>

    <%= f.label : %>
    <%= f.password_field : %><br>

    <%= f.submit %>
<% end %>

BASIC NESTED FORM 
<%= form_with(model: @post, url: form_url_helper(@invasive_species)) do |f| %>
    <% if !@invasive_species %>
        <%= f.label :invasive_species %><br>
        <%= f.fields_for :invasive_species do |i| %>
            <%= i.label :common_name %>
            <%= i.text_field :common_name %>
        <% end %><br>
    <% end %>
...continue with normal form with