config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  resources :posts
  resources :invasive_species do
    resources :posts, except: [:index]
  end

  resources :users

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/invasive_species_controller.rb
class InvasiveSpeciesController < ApplicationController
    before_action :require_login

    def index
        if params[:search]
            @all_species = InvasiveSpecies.name_includes(params[:search])
        else
            @all_species = InvasiveSpecies.all
        end
    end
    
    def new
        @invasive_species = InvasiveSpecies.new
    end

    def create
        if new_species = InvasiveSpecies.find_by(common_name: species_params[:common_name])
            flash[:failure] = "That species already exists. Please feel free to add a post to it about what you found!"
            redirect_to invasive_specy_path(new_species)
        else new_species = InvasiveSpecies.create(common_name: species_params[:common_name], description: species_params[:description])
            if new_species.save
                redirect_to invasive_specy_path(new_species)
            else
                flash[:failure] = new_species.errors.full_messages
                render :new
            end
        end
    end

    def show
        @invasive_species = InvasiveSpecies.find_by(id: params[:id])
        @posts = @invasive_species.posts
    end

    def edit
        @invasive_species = InvasiveSpecies.find_by(id: params[:id])
        if !current_user.admin
            flash[:failure] = "Only administrators can edit this species. Please make a post for potential edits. Please start your post with *Requested Edit.*"
            redirect_to invasive_specy_path(@invasive_species)
        end
    end

    def update
        @invasive_species = InvasiveSpecies.find_by(id: params[:id])

        if @invasive_species.update(species_params)
            redirect_to invasive_specy_path(@invasive_species)
        else
            flash[:failure] = "Edits not saved. Did you leave the species name blank?"
            render :edit
        end
    end

    def destroy
        redirect_if_not_admin
        @invasive_species = InvasiveSpecies.find_by(id: params[:id])
        @invasive_species.destroy
    end

    private

    def species_params
        params.require(:invasive_species).permit(:common_name, :photo, :description, :environment)
    end
end

app/helpers/invasive_species_helper.rb
module InvasiveSpeciesHelper
end

app/views/invasive_species/_form.html.erb
    
<%= form_with(model: @invasive_species, url: invasive_species_path) do |f| %>
    <%= f.label :common_name %>
    <%= f.text_field :common_name %><br>

    <%= f.label "Defining Characteristics of this Species: growth pattern, origin history, environment preference, range, etc" %>
    <%= f.text_area :description %> <br>

    <%= f.submit %>
<% end %>
    

app/views/invasive_species/index.html.erb
<%= form_tag invasive_species_path, method: :get do %>
    <%= label_tag "Search by Name:" %>
    <%= text_field_tag :search %>
    <%= submit_tag :search %>
<% end %>

<% @all_species.each do |s| %>
    <%= s.common_name %><br>
<% end %>

app/views/invasive_species/new.html.erb
<%= render 'form' %>

app/views/invasive_species/show.html.erb
<div>
    <h1><%= @invasive_species.common_name %></h1>
    <h4><%= @invasive_species.description %></h4>
</div><br>

<%= render 'posts/index' %>

<div>
    <% @posts.each do |s| %>
      <div>
        <%= s.description %><br>
        <%= s.location_latitude %>
        <%= s.location_longitude %><br>

        <% if s.updated_at != s.created_at %>
            <span>Post updated at</span>
            <%= s.updated_at %>
        <% else %>
            <span>Post created at</span>
            <%= s.created_at %>
        <% end %>
      </div><br>
    <% end %>
</div>