config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  resources :posts
  resources :invasive_species do
    resources :posts, except: [:index]
  end

  resources :users

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_alerts.html.erb
<div class="container">
    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %>">
        <% if Array === message %>
            <ul>
            <% message.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        <% else %>
            <%= message %>
        <% end %>
      </div>
    <% end %>
</div>


<div class="container">
  <% flash.each do |key, msg| %>
    <div class="alert alert-<%=key%> alert-dismissible fade show" role="alert">
      <h6><strong><%= msg %></strong></h6>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsInvasiveSpeciesTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <link href="assets/bootstrap.min.css" media="all" rel="stylesheet" />
    

   <script src="/assets/bootstrap.min.js"></script>

  
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="invasive_species">
          <img src="app/assets/images/leaf_logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          Plant.Spy
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%# <a  href="/signup">Sign Up<span class="sr-only">(current)</span></a>   #do I need this in the line below? <span class="sr-only">(current)</span> %>
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, method: :post, class: "nav-link" %>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Create New
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/invasive_species/new">New Species</a>
                  <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/posts/new">New Post</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      <div id="page-content">
        <%= render 'layouts/flash_alerts'%>
      </div>
    </header>
    <%= yield %>
  </body>
</html>